### ISSUE TITLE
Which IDE is everyone using currently?

### ISSUE THREAD

**Issue by josephLeiferman** [dhuang12138/Group_B3#6]

**Comment by weigui** [comment]
Eclipse

**Comment by weigui** [comment]
by the way, please chat here:
https://github.com/dhuang12138/Group_B3/issues/3

**Comment by dhuang12138** [comment]
Eclipse for sure.

**Comment by dhuang12138** [comment]
@josephLeiferman  you'd better keep a branch and backup your work there

**Comment by josephLeiferman** [comment]
I have moved all my to the master, that is why floor branch is gone.
