### ISSUE TITLE
Errors on the master branch

### ISSUE THREAD

**Issue by josephLeiferman** [dhuang12138/Group_B3#9]
Hi everyone, if everyone could pull from the master and and push their most current work sometime before Sunday that would be great. There about 13 errors on the on the master branch we should try to get rid of before Monday. If you have question about the work that I have done with the floor feel free to ask me. Also my number is 630-414-3666 if you want a quicker response. Have a good weekend everyone.

**Comment by weigui** [comment]
Got it

**Comment by NickEBarnes** [comment]
Sorry I haven't been able to do a whole with the project. I'm going to work on it here shortly for the night. Sorry again!
________________________________

**Comment by weigui** [comment]
There is no error now.
